version: '3'

services:

  sql:
    image: postgres:11.2-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB1_PASS}
      - POSTGRES_USER=${DB1_USER}
      - POSTGRES_DB=${DB1_NAME}
    volumes:
      - ./db/data/db1:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/

  dba:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${DBA_PASS}
      - PGADMIN_DEFAULT_EMAIL=${DBA_USER}
      - PGADMIN_PORT=80
    depends_on:
      - sql
    ports:
      - ${DBA_PORT}:80

  app:
    image: douglascarlini/php:7.2
    restart: always
    env_file: .env
    depends_on:
      - sql
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./src:/var/www/html
